FROM httpd AS files

FROM debian

LABEL org.opencontainers.image.source=https://github.com/xJonathanLEI/ab

COPY --from=files /usr/lib/aarch64-linux-gnu/libapr-1.so.0 /usr/lib/aarch64-linux-gnu/libaprutil-1.so.0 /lib/aarch64-linux-gnu/libexpat.so.1 /usr/lib/aarch64-linux-gnu/
COPY --from=files /usr/local/apache2/bin/ab /usr/bin/ab

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "ab" ]
