name: Build Multi-Arch Images

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: xjonathanlei/ab

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Enable Docker Buildx
        run: |
          jq '. + {"experimental":"enabled"}' ~/.docker/config.json > ~/.docker/config_new.json
          mv ~/.docker/config_new.json ~/.docker/config.json
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo systemctl restart docker
          docker buildx create --name multi_builder
          docker buildx use multi_builder

      - name: Build vanilla linux/amd64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:amd64 -f ./vanilla/Dockerfile.amd64 --platform linux/amd64 --output=type=docker .

      - name: Build vanilla linux/arm64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:arm64 -f ./vanilla/Dockerfile.arm64 --platform linux/arm64 --output=type=docker .

      - name: Build with-curl linux/amd64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:curl-amd64 -f ./with-curl/Dockerfile.amd64 --platform linux/amd64 --output=type=docker .

      - name: Build with-curl linux/arm64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:curl-arm64 -f ./with-curl/Dockerfile.arm64 --platform linux/arm64 --output=type=docker .

      - name: Push Multi-Arch Images
        run: |
          docker push ${DOCKER_REPOSITORY}:amd64
          docker push ${DOCKER_REPOSITORY}:arm64
          docker push ${DOCKER_REPOSITORY}:curl-amd64
          docker push ${DOCKER_REPOSITORY}:curl-arm64
          docker manifest create ${DOCKER_REPOSITORY}:curl \
            ${DOCKER_REPOSITORY}:curl-amd64 \
            ${DOCKER_REPOSITORY}:curl-arm64
          docker manifest create ${DOCKER_REPOSITORY}:latest \
            ${DOCKER_REPOSITORY}:amd64 \
            ${DOCKER_REPOSITORY}:arm64
          docker manifest push ${DOCKER_REPOSITORY}:curl
          docker manifest push ${DOCKER_REPOSITORY}:latest
